const ADD_TO_CART = "ADD_TO_CART";
const REMOVE_FROM_CART = "REMOVE_FROM_CART";
const ADD_TO_LIKEBOX = "ADD_TO_LIKEBOX";
const REMOVE_FROM_LIKEBOX = "REMOVE_FROM_LIKEBOX";
const ADD_ONE = "ADD_ONE";
const REMOVE_ONE = "REMOVE_ONE";

export {
    ADD_TO_CART,
    REMOVE_FROM_CART,
    ADD_TO_LIKEBOX,
    REMOVE_FROM_LIKEBOX,
    ADD_ONE,
    REMOVE_ONE,
};
